pluginGroup=com.github.pablolec
pluginName=Play v1 Toolkit
pluginVersion=0.1.0-SNAPSHOT
pluginRepositoryUrl=https://github.com/PabloLec/play1-intellij-plugin

# IntelliJ Platform target
platformType=IU
platformVersion=2026.1.2

# Build range
pluginSinceBuild=261
gradleVersion=9.5.1

# Gradle
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.stdlib.default.dependency=false
